name: Electron Build and Package

on:
  push:
    branches:
      - main

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust to the version you're using

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npm run build

    - name: Package Electron app
      run: npm run package
      # Ensure you have a package script in your package.json for Electron
